import { MongoClient } from 'mongodb';
import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import fetch from 'node-fetch';

dotenv.config();

const app = express();
app.use(cors());
app.use(express.json());

// 🔹 Hardcoded MongoDB URI (make sure to include your password!)
// Make sure 'ps' is your correct password
const uri = "mongodb+srv://Mishty:pswd@cluster0.fj57vdo.mongodb.net/?appName=Cluster0";
const client = new MongoClient(uri);

async function connectDB() {
    try {
        await client.connect();
        console.log("✅ Connected successfully to MongoDB");
        // Return the client itself, or a specific DB if you prefer
        // Returning the client is often more flexible.
        return client; 
    } catch (error) {
        console.error('❌ Database connection failed:', error);
        // Ensure the app exits or handles this gracefully
        // For this example, we'll let the caller handle the error.
        throw new Error('Failed to connect to the database.');
    }
}

// Helper to get the database instance
async function getDb() {
    // Check if client is already connected
    if (!client.topology || !client.topology.isConnected()) {
        await connectDB();
    }
    // Explicitly selecting the 'ncert_rag' database
    return client.db('ncert_rag'); 
}

async function getUserData(auth_user_id) {
    const db = await getDb(); // Use helper to get DB
    const user = await db.collection('users').findOne({ auth_user_id });
    if (!user) {
        throw new Error('User not found.');
    }
    return user;
}

// ✅ Fixed Gemini API call
async function callRAGModel(prompt) {
    const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
    if (!GEMINI_API_KEY) throw new Error("Missing GEMINI_API_KEY in environment");

    // Using v1 and gemini-1.5-flash
    const API_URL = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${GEMINI_API_KEY}`;

    // Using snake_case ("response_mime_type") as required by the v1 API
    const requestBody = {
        contents: [{
            parts: [{ text: prompt }]
        }],
        generationConfig: {
            response_mime_type: "application/json", // Request JSON output
        }
    };

    const response = await fetch(API_URL, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json'
        },
        body: JSON.stringify(requestBody)
    });

    const data = await response.json();

    if (!response.ok) {
        console.error("Gemini API error:", data);
        const errorDetails = data.error?.message || response.statusText;
        throw new Error(`Failed to call Gemini API: ${errorDetails}`);
    }
    
    // ✅ Extract model output correctly (it should be a JSON string)
    const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text;
    
    if (!generatedText) {
        // Check if the response was blocked
        if (data.candidates?.[0]?.finishReason === 'SAFETY') {
            throw new Error("Model response blocked due to safety settings.");
        }
        throw new Error("No response text generated by the model.");
    }
    
    // Parse the JSON string from the model
    try {
        const jsonData = JSON.parse(generatedText);
        return jsonData; // Return the parsed JSON object
    } catch (parseError) {
        console.error("Failed to parse JSON response from model:", generatedText);
        throw new Error("Model did not return valid JSON.");
    }
}


// --- ⬇️ REFINED RAG FUNCTION FOR FLASHCARDS ⬇️ ---

/**
 * Generates NCERT-based, personalized flashcards using RAG
 * with hierarchical performance logic.
 */
async function generateFlashcards(auth_user_id, requestBody) {
    const { subject, topic } = requestBody;

    if (!subject || !topic) {
        throw new Error("Missing 'subject' or 'topic' in request body.");
    }

    // --- 1. RETRIEVAL ---
    const userData = await getUserData(auth_user_id);
    const { class: userClass, performance_summary } = userData;

    // --- 2. AUGMENTATION (with new hierarchical logic) ---
    let performanceProfile = "No specific performance data available.";
    let difficultyRequest = "a standard mix of foundational and application questions";

    try {
        const subjectData = performance_summary?.by_subject?.[subject];
        const chapterData = subjectData?.by_chapter?.[topic];

        // Helper function to parse performance numbers
        const getNum = (field) => parseFloat(field?.$numberDouble || field || 0);

        if (chapterData) {
            // RULE 1: Use specific chapter/topic data
            const chapterStrength = chapterData.strength_level || 'moderate';
            const chapterAccuracy = (getNum(chapterData.accuracy) * 100).toFixed(0);
            
            performanceProfile = `Student has specific data for this topic: **Strength: ${chapterStrength}**, **Accuracy: ${chapterAccuracy}%**.`;

            if (chapterStrength === 'weak') {
                difficultyRequest = "focus heavily on **basic-intermediate definitions and foundational formulas**. The student is weak in this specific topic.";
            } else if (chapterStrength === 'strong') {
                difficultyRequest = "focus on **difficult, complex, and multi-step application-based questions**. The student is strong in this topic.";
            } else { // moderate
                difficultyRequest = "a mix of foundational concepts and moderately complex application problems. The student has moderate strength here.";
            }

        } else if (subjectData) {
            // RULE 2: No topic data, use subject data
            const subjectStrength = subjectData.strength_level || 'moderate';
            
            performanceProfile = `No data for this specific topic. Using overall **${subject}** subject data: **Strength: ${subjectStrength}**.`;

            if (subjectStrength === 'weak') {
                difficultyRequest = "focus on **basic-intermediate concepts** for this topic, as the student is generally weak in ${subject}.";
            } else if (subjectStrength === 'strong') {
                difficultyRequest = "focus on **difficult and complex questions**, as the student is generally strong in ${subject}.";
            } else { // moderate
                difficultyRequest = "a mix of foundational concepts and moderately complex application problems.";
            }

        } else if (performance_summary?.overall_accuracy) {
            // RULE 3: No topic or subject data, use overall performance
            const overallAccuracy = getNum(performance_summary.overall_accuracy);
            const overallAccuracyPercent = (overallAccuracy * 100).toFixed(0);
            
            performanceProfile = `No topic or subject data. Using **overall performance: ${overallAccuracyPercent}% accuracy**.`;

            if (overallAccuracy < 0.6) { // Weaker student
                difficultyRequest = "focus on **common topics for board exams** and provide **better, more detailed explanations** in the answers. The student has a weaker overall performance.";
            } else if (overallAccuracy > 0.8) { // Stronger student
                difficultyRequest = "focus on **complex, lesser-known facts, and advanced application questions**. The student has a strong overall performance.";
            } else { // Moderate student
                difficultyRequest = "a standard mix of foundational concepts and common application problems. The student has a moderate overall performance.";
            }
        }
        // RULE 4 (Default): If no data exists at all, the default values are used.

    } catch (e) {
        console.warn("Could not build performance profile:", e.message);
        // Errors in this block are non-fatal; we'll just use the default profile.
    }

    // --- 3. GENERATION ---
    // Inject the retrieved context into the prompt
    const prompt = `
    You are an expert academic tutor for Indian students. Your task is to generate high-quality, personalized flashcards.

    **Constraints & Rules:**
    1.  **Source:** All information MUST be derived *exclusively* from the NCERT textbook.
    2.  **Audience:** Class ${userClass} (PCM Stream).
    3.  **Format:** You MUST output *only* a valid JSON object.
    4.  **Personalization:** You MUST tailor the flashcards based on the student's performance.

    **Input:**
    * **Class:** ${userClass}
    * **Subject:** ${subject}
    * **Topic:** ${topic}

    **--- 💡 STUDENT PERFORMANCE PROFILE (RAG) 💡 ---**
    * **Profile:** ${performanceProfile}
    * **Action:** Based on this profile, ${difficultyRequest}.
    **--- -------------------------------------- ---**

    **Required JSON Output Structure:**
    {
      "flashcards": [
        {
          "front": "<Question, Term, or 'Define: ...'>",
          "back": "<Concise, NCERT-based answer or definition>"
        },
        {
          "front": "<Another question or formula name...>",
          "back": "<The corresponding answer or formula...>"
        }
      ]
    }

    Generate 10-15 flashcards for the topic: "${topic}" from the ${subject} NCERT textbook.
    `;
    // --- 🔸 END OF PROMPT 🔸 ---

    console.log(`Generating flashcards for Class ${userClass}, ${subject}, ${topic}...`);
    console.log(`Using profile: ${performanceProfile}`); // Log the profile for debugging
    
    const response = await callRAGModel(prompt);
    
    // Add context to the response before sending it back
    return {
        subject,
        topic,
        class: userClass,
        _debug_RAG_profile: performanceProfile, // Send profile to client for debugging
        ...response // This will include the "flashcards": [...] array
    };
}

// --- ⬆️ END OF REFINED FUNCTION ⬆️ ---


// --- ⬇️ API ENDPOINT FOR FLASHCARDS ⬇️ ---
app.post('/generate-flashcards', async (req, res) => {
    try {
        const auth_user_id = req.headers.authorization?.split(' ')[1];
        if (!auth_user_id) {
            return res.status(401).json({ error: 'Authorization required' });
        }

        // Pass the request body which should contain { "subject": "...", "topic": "..." }
        const flashcardData = await generateFlashcards(auth_user_id, req.body);
        
        res.json(flashcardData); // Send the parsed JSON object

    } catch (error) {
        console.error('❌ Error in /generate-flashcards:', error.message);
        // Differentiate between user error (e.g., bad input) and server error
        if (error.message.includes("Missing")) {
            res.status(400).json({ error: error.message }); // 400 Bad Request
        } else {
            res.status(500).json({ error: error.message }); // 500 Internal Server Error
        }
    }
});
// --- ⬆️ END OF NEW ENDPOINT ⬆️ ---


const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
    console.log(`🚀 Server running on port ${PORT}`);
    connectDB().catch(console.error); // Initial connection attempt
});