import assert from 'node:assert/strict';
import { isPassPlan, validPassProduct, verifyPaymentWebhook } from './curve-billing';
assert.equal(isPassPlan('monthly'), true);
assert.equal(isPassPlan('semester'), true);
for (const value of ['annual', '', null, {}, 'MONTHLY']) assert.equal(isPassPlan(value), false);
const product = { is_recurring: false, price: { type: 'one_time_price', currency: 'USD', price: 1299 } };
assert.equal(validPassProduct(product, 'monthly'), true);
assert.equal(validPassProduct(product, 'semester'), false);
assert.equal(validPassProduct({ ...product, is_recurring: true }, 'monthly'), false);
assert.equal(validPassProduct({ ...product, price: { ...product.price, pay_what_you_want: true } }, 'monthly'), false);
assert.equal(validPassProduct({ ...product, price: { ...product.price, currency: 'INR' } }, 'monthly'), false);
const secretBytes = new TextEncoder().encode('fixture-signing-key-do-not-use');
const secret = 'whsec_' + btoa(String.fromCharCode(...secretBytes));
const now = Date.now(), timestamp = String(Math.floor(now / 1000));
const body = JSON.stringify({ type: 'payment.succeeded', data: { payment_id: 'pay_fixture' } });
const key = await crypto.subtle.importKey('raw', secretBytes, { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']);
const sig = await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(`evt_fixture.${timestamp}.${body}`));
const headers = new Headers({ 'webhook-id': 'evt_fixture', 'webhook-timestamp': timestamp, 'webhook-signature': 'v1,' + btoa(String.fromCharCode(...new Uint8Array(sig))) });
assert.equal(await verifyPaymentWebhook(body, headers, secret, now), true);
assert.equal(await verifyPaymentWebhook(body + ' ', headers, secret, now), false);
assert.equal(await verifyPaymentWebhook(body, headers, secret, now + 301000), false);
assert.equal(await verifyPaymentWebhook(body, headers, '', now), false);
assert.equal(await verifyPaymentWebhook(body, new Headers(), secret, now), false);
headers.set('webhook-id', 'evt_other');
assert.equal(await verifyPaymentWebhook(body, headers, secret, now), false);
console.log('Billing checks passed: plans, product configuration, signed payload, tampering, timestamp, missing secret, replay identity.');
