import React, { useState, useEffect, useRef } from 'react';
import { Brain, Check, Star, Zap, Users, BarChart3, Crown, ArrowRight, Play, Shield, Sparkles, Target, BookOpen, TrendingUp, ExternalLink, MessageCircle, User } from 'lucide-react';
import { useAuth } from '../contexts/AuthContext';
import { useToast } from '../hooks/useToast';
import gsap from 'gsap';
import ScrollTrigger from 'gsap/ScrollTrigger';
import { supabase } from '../lib/supabase';

gsap.registerPlugin(ScrollTrigger);

export function Landing() {
  const { signUp, signIn } = useAuth();
  const { showToast } = useToast();
  const [isSignUp, setIsSignUp] = useState(true);
  const [loading, setLoading] = useState(false);
  const [formData, setFormData] = useState({
    email: '',
    password: '',
    full_name: '',
    grade: '',
    school: ''
  });

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);

    try {
      if (isSignUp) {
        const { error } = await signUp(formData.email, formData.password, {
          full_name: formData.full_name,
          grade: formData.grade,
          school: formData.school
        });
        if (error) throw error;
        showToast('Account created! Welcome to STUBUD!', 'success');
      } else {
        const { error } = await signIn(formData.email, formData.password);
        if (error) throw error;
        showToast('Welcome back to STUBUD!', 'success');
      }
    } catch (error: any) {
      showToast(error.message, 'error');
    } finally {
      setLoading(false);
    }
  };

  const handleGoogleSignIn = async () => {
    setLoading(true);
    try {
      const { error } = await supabase.auth.signInWithOAuth({ provider: 'google' });
      if (error) throw error;
      // Supabase will redirect on success
    } catch (error: any) {
      showToast(error.message || 'Google sign-in failed', 'error');
    } finally {
      setLoading(false);
    }
  };

  const features = [
    {
      icon: Brain,
      title: 'AI-Powered Study Plans',
      description: 'Get personalized study schedules generated by advanced AI based on your exam dates and subjects.',
      color: 'from-blue-500 to-cyan-500'
    },
    {
      icon: Zap,
      title: 'Smart Flashcards',
      description: 'AI-generated flashcards with spaced repetition and topic-based review for maximum retention.',
      color: 'from-purple-500 to-pink-500'
    },
    {
      icon: Target,
      title: 'Practice Test Engine',
      description: 'Unlimited AI-generated practice tests tailored to your curriculum with instant feedback.',
      color: 'from-green-500 to-emerald-500'
    },
    {
      icon: BarChart3,
      title: 'Advanced Analytics',
      description: 'Deep insights into your learning patterns, progress tracking, and AI-powered recommendations.',
      color: 'from-orange-500 to-red-500'
    },
    {
      icon: Users,
      title: 'Study Groups & Social',
      description: 'Join private study groups, share notes, compete on leaderboards, and collaborate with friends.',
      color: 'from-indigo-500 to-purple-500'
    },
    {
      icon: TrendingUp,
      title: 'Progress Tracking',
      description: 'Comprehensive progress monitoring with streak tracking, achievements, and performance metrics.',
      color: 'from-teal-500 to-blue-500'
    },
    {
      icon: BookOpen,
      title: 'Live Meeting Notes',
      description: 'Real-time speech-to-text note-taking with AI formatting and screenshot capture.',
      color: 'from-pink-500 to-yellow-500'
    },
    {
      icon: Sparkles,
      title: 'Smart Notifications',
      description: 'AI-powered reminders and motivational nudges to keep you on track.',
      color: 'from-yellow-400 to-orange-400'
    },
    {
      icon: Shield,
      title: 'Calendar Sync',
      description: 'Sync your study plans and deadlines with your favorite calendar apps.',
      color: 'from-blue-400 to-green-400'
    },
    {
      icon: Crown,
      title: 'Achievements & Streaks',
      description: 'Earn badges, track streaks, and celebrate your study milestones.',
      color: 'from-yellow-500 to-pink-500'
    },
    {
      icon: MessageCircle,
      title: 'AI Study Buddy Chat',
      description: 'Chat with an AI tutor for instant explanations, step-by-step solutions, and personalized study help. Integrated with your study plans and supports voice input!',
      color: 'from-pink-500 to-red-500'
    }
  ];

  const testimonials = [
    {
      name: 'Priya Sharma',
      grade: 'Class 12',
      text: 'STUBUD helped me improve my JEE preparation by 40%. The personalized study plans are incredible!',
      rating: 5
    },
    {
      name: 'Arjun Patel',
      grade: 'Class 10',
      text: 'The AI flashcards and practice tests made studying so much more effective. Highly recommend!',
      rating: 5
    },
    {
      name: 'Sneha Reddy',
      grade: 'Class 11',
      text: 'Study groups feature helped me connect with other students. We motivate each other every day!',
      rating: 5
    }
  ];

  const pricingFeatures: any[] = [];

  // GSAP animation refs
  const heroRef = useRef<HTMLDivElement>(null);
  const featuresRef = useRef<HTMLDivElement>(null);
  const testimonialsRef = useRef<HTMLDivElement>(null);
  const heroHeadlineRef = useRef<HTMLHeadingElement>(null);
  const heroSubheadlineRef = useRef<HTMLParagraphElement>(null);
  const heroIconsRef = useRef<HTMLSpanElement>(null);
  const bgBlob1Ref = useRef<HTMLDivElement>(null);
  const bgBlob2Ref = useRef<HTMLDivElement>(null);
  const bgBlob3Ref = useRef<HTMLDivElement>(null);
  const featureCardsRef = useRef<HTMLDivElement>(null);
  const testimonialsSectionRef = useRef<HTMLDivElement>(null);
  const ctaSectionRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const tl = gsap.timeline();

    // Hero headline and subheadline
    tl.from(heroHeadlineRef.current, { opacity: 0, y: 60, duration: 1, ease: 'power4.out' })
      .from(heroSubheadlineRef.current, { opacity: 0, y: 40, duration: 0.8, ease: 'power4.out' }, '-=0.6');

    // Hero icons
    if (heroIconsRef.current) {
      gsap.fromTo(
        (heroIconsRef.current as HTMLSpanElement).querySelectorAll('.hero-icon'),
        { opacity: 0, scale: 0.7, y: 30 },
        { opacity: 1, scale: 1, y: 0, duration: 0.7, stagger: 0.15, ease: 'back.out(1.7)', delay: 0.2 }
      );
    }

    // Background blobs floating
    [bgBlob1Ref, bgBlob2Ref, bgBlob3Ref].forEach((ref, i) => {
      if (ref.current) {
        gsap.to(ref.current, {
          y: i % 2 === 0 ? '+=40' : '-=40',
          x: i === 1 ? '+=30' : '-=30',
          repeat: -1,
          yoyo: true,
          duration: 6 + i * 2,
          ease: 'sine.inOut',
        });
      }
    });

    // Parallax blobs on scroll
    [bgBlob1Ref, bgBlob2Ref, bgBlob3Ref].forEach((ref, i) => {
      if (ref.current) {
        gsap.to(ref.current, {
          yPercent: i === 0 ? 10 : i === 1 ? -10 : 5,
          scrollTrigger: {
            trigger: ref.current,
            start: 'top bottom',
            end: 'bottom top',
            scrub: 1,
          },
        });
      }
    });

    // Feature cards 3D entrance
    if (featureCardsRef.current) {
      gsap.fromTo(
        (featureCardsRef.current as HTMLDivElement).querySelectorAll('.feature-card'),
        { opacity: 0, y: 60, rotateY: 30, scale: 0.8 },
        {
          opacity: 1,
          y: 0,
          rotateY: 0,
          scale: 1,
          duration: 1,
          stagger: 0.15,
          ease: 'power3.out',
          scrollTrigger: {
            trigger: featureCardsRef.current,
            start: 'top 80%',
          },
        }
      );
    }

    // Testimonials fade/slide on scroll
    if (testimonialsSectionRef.current) {
      gsap.fromTo(
        (testimonialsSectionRef.current as HTMLDivElement).querySelectorAll('.testimonial-card'),
        { opacity: 0, y: 60, scale: 0.95 },
        {
          opacity: 1,
          y: 0,
          scale: 1,
          duration: 1,
          stagger: 0.2,
          ease: 'power3.out',
          scrollTrigger: {
            trigger: testimonialsSectionRef.current,
            start: 'top 80%',
          },
        }
      );
    }

    // CTA section entrance
    if (ctaSectionRef.current) {
      gsap.fromTo(
        ctaSectionRef.current,
        { opacity: 0, y: 60 },
        {
          opacity: 1,
          y: 0,
          duration: 1,
          ease: 'power3.out',
          scrollTrigger: {
            trigger: ctaSectionRef.current,
            start: 'top 90%',
          },
        }
      );
    }
  }, []);

  return (
    <div className="min-h-screen bg-gray-900 overflow-hidden">
      {/* Animated Background */}
      <div className="animated-gradient fixed inset-0 opacity-20"></div>
      <div className="absolute inset-0 overflow-hidden">
        <div className="absolute top-20 left-20 w-72 h-72 bg-blue-500/10 rounded-full blur-3xl animate-pulse"></div>
        <div className="absolute bottom-20 right-20 w-96 h-96 bg-purple-500/10 rounded-full blur-3xl animate-pulse animation-delay-1000"></div>
        <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-64 h-64 bg-cyan-500/10 rounded-full blur-3xl animate-pulse animation-delay-2000"></div>
      </div>

      <div className="relative z-10">
        {/* Hero Section */}
        <section ref={heroRef} className="min-h-screen flex items-center justify-center px-4 py-20">
          <div className="w-full max-w-3xl mx-auto bg-white/10 rounded-3xl shadow-2xl p-8 flex flex-col items-center">
            {/* 7-day free badge */}
            <div className="mb-6 flex flex-col items-center">
              <span className="inline-block bg-gradient-to-r from-green-400 to-blue-500 text-white font-bold px-5 py-2 rounded-full text-lg shadow-lg mb-2 animate-bounce">
                🎉 7 Days Free – No Credit Card Required
              </span>
              <span className="text-blue-200 text-sm">Try all premium features for 7 days, risk-free!</span>
            </div>
            <div className="max-w-7xl mx-auto grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
              {/* Left Side - Content */}
              <div className="text-center lg:text-left">
                <div className="flex items-center justify-center lg:justify-start gap-3 mb-6">
                  <div className="relative">
                    <div className="bg-gradient-to-br from-blue-500 to-purple-600 p-4 rounded-2xl shadow-2xl glow-blue">
                      <Brain className="h-12 w-12 text-white" />
                    </div>
                    <Sparkles className="absolute -top-2 -right-2 h-8 w-8 text-yellow-400 animate-bounce" />
                    <Star className="absolute -bottom-1 -left-1 h-6 w-6 text-cyan-400 animate-pulse" />
                  </div>
                  <div>
                    <h1 ref={heroHeadlineRef} className="text-5xl lg:text-6xl font-bold gradient-text">
                      STUBUD
                    </h1>
                    <p ref={heroSubheadlineRef} className="text-blue-300 text-lg">Your AI Study Buddy</p>
                  </div>
                </div>

                <h2 className="text-4xl lg:text-5xl font-bold text-white mb-6 leading-tight">
                  Transform Your Study Experience with{' '}
                  <span ref={heroIconsRef} className="gradient-text">AI Intelligence</span>
                </h2>

                <p className="text-xl text-gray-300 mb-8 leading-relaxed">
                  Get personalized study plans, AI-generated flashcards, practice tests, and advanced analytics. 
                  Join thousands of students who've improved their grades by 40% on average.
                </p>

                <div className="flex flex-col sm:flex-row items-center justify-center gap-4 mb-8">
                  <a
                    href="/ai-study-buddy"
                    className="inline-flex items-center gap-2 bg-gradient-to-r from-pink-600 to-red-500 text-white px-6 py-3 rounded-xl font-semibold shadow-lg hover:from-pink-700 hover:to-red-600 transition-all duration-300 text-lg"
                  >
                    <MessageCircle className="h-6 w-6" />
                    Try the new AI Study Buddy Chat!
                  </a>
                  <span className="text-pink-300 text-sm">Ask questions, get explanations, and more — instantly!</span>
                </div>
              </div>

              {/* Right Side - Auth Form */}
              <div className="glass rounded-2xl border border-gray-700/50 p-8 card-hover">
                <div className="text-center mb-6">
                  <h3 className="text-2xl font-bold text-white mb-2">
                    {isSignUp ? 'Join STUBUD Today' : 'Welcome Back'}
                  </h3>
                  <p className="text-gray-400">
                    {isSignUp ? 'Start your AI-powered learning journey' : 'Continue your learning journey'}
                  </p>
                </div>

                <form onSubmit={handleSubmit} className="space-y-4">
                  {isSignUp && (
                    <>
                      <input
                        type="text"
                        required
                        value={formData.full_name}
                        onChange={(e) => setFormData(prev => ({ ...prev, full_name: e.target.value }))}
                        className="w-full px-4 py-3 rounded-xl bg-gray-800/50 border border-gray-600 focus:border-blue-500 focus:outline-none transition-all duration-300 text-white placeholder-gray-400"
                        placeholder="Full Name"
                      />
                      <div className="grid grid-cols-2 gap-4">
                        <input
                          type="text"
                          required
                          value={formData.grade}
                          onChange={(e) => setFormData(prev => ({ ...prev, grade: e.target.value }))}
                          className="w-full px-4 py-3 rounded-xl bg-gray-800/50 border border-gray-600 focus:border-blue-500 focus:outline-none transition-all duration-300 text-white placeholder-gray-400"
                          placeholder="Grade/Class"
                        />
                        <input
                          type="text"
                          value={formData.school}
                          onChange={(e) => setFormData(prev => ({ ...prev, school: e.target.value }))}
                          className="w-full px-4 py-3 rounded-xl bg-gray-800/50 border border-gray-600 focus:border-blue-500 focus:outline-none transition-all duration-300 text-white placeholder-gray-400"
                          placeholder="School"
                        />
                      </div>
                    </>
                  )}

                  <input
                    type="email"
                    required
                    value={formData.email}
                    onChange={(e) => setFormData(prev => ({ ...prev, email: e.target.value }))}
                    className="w-full px-4 py-3 rounded-xl bg-gray-800/50 border border-gray-600 focus:border-blue-500 focus:outline-none transition-all duration-300 text-white placeholder-gray-400"
                    placeholder="Email Address"
                  />

                  <input
                    type="password"
                    required
                    value={formData.password}
                    onChange={(e) => setFormData(prev => ({ ...prev, password: e.target.value }))}
                    className="w-full px-4 py-3 rounded-xl bg-gray-800/50 border border-gray-600 focus:border-blue-500 focus:outline-none transition-all duration-300 text-white placeholder-gray-400"
                    placeholder="Password"
                    minLength={6}
                  />

                  <div className="mt-6 flex flex-col gap-3">
                    <button
                      type="button"
                      onClick={handleGoogleSignIn}
                      disabled={loading}
                      className="w-full flex items-center justify-center gap-3 bg-white text-gray-800 font-semibold py-3 px-6 rounded-xl border border-gray-300 shadow hover:bg-gray-50 transition-all duration-300 disabled:opacity-60 disabled:cursor-not-allowed"
                    >
                      <span className="inline-block h-6 w-6">
                        <svg viewBox="0 0 48 48" width="24" height="24">
                          <g>
                            <path fill="#4285F4" d="M24 9.5c3.54 0 6.36 1.53 7.82 2.81l5.77-5.77C34.13 3.36 29.54 1 24 1 14.82 1 6.98 6.98 3.69 15.09l6.91 5.36C12.13 14.36 17.56 9.5 24 9.5z"/>
                            <path fill="#34A853" d="M46.1 24.5c0-1.64-.15-3.22-.43-4.74H24v9.01h12.42c-.54 2.9-2.18 5.36-4.66 7.01l7.19 5.6C43.98 37.02 46.1 31.25 46.1 24.5z"/>
                            <path fill="#FBBC05" d="M10.6 28.45c-1.04-3.09-1.04-6.41 0-9.5l-6.91-5.36C1.64 17.36 0 20.54 0 24c0 3.46 1.64 6.64 3.69 9.41l6.91-5.36z"/>
                            <path fill="#EA4335" d="M24 46.5c5.54 0 10.13-1.82 13.44-4.97l-7.19-5.6c-2.01 1.35-4.59 2.14-7.25 2.14-6.44 0-11.87-4.86-13.4-11.36l-6.91 5.36C6.98 41.02 14.82 46.5 24 46.5z"/>
                            <path fill="none" d="M0 0h48v48H0z"/>
                          </g>
                        </svg>
                      </span>
                      {loading ? 'Signing in...' : 'Sign in with Google'}
                    </button>
                  </div>

                  <button
                    type="submit"
                    disabled={loading}
                    className="w-full bg-gradient-to-r from-green-600 to-emerald-600 hover:from-green-700 hover:to-emerald-700 disabled:from-gray-600 disabled:to-gray-700 text-white font-bold py-3 px-6 rounded-xl transition-all duration-300 disabled:cursor-not-allowed"
                  >
                    {loading ? (
                      <div className="flex items-center justify-center gap-2">
                        <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin"></div>
                        Please wait...
                      </div>
                    ) : (
                      isSignUp ? 'Create Account' : 'Sign In'
                    )}
                  </button>
                </form>

                <div className="mt-6 text-center">
                  <button
                    onClick={() => setIsSignUp(!isSignUp)}
                    className="text-blue-400 hover:text-blue-300 font-medium transition-colors duration-200"
                  >
                    {isSignUp ? 'Already have an account? Sign in' : "Don't have an account? Join STUBUD"}
                  </button>
                </div>

                {isSignUp && (
                  <div className="mt-4 text-center">
                    <p className="text-xs text-gray-500">
                      By signing up, you agree to our Terms of Service and Privacy Policy
                    </p>
                  </div>
                )}
              </div>
            </div>
          </div>
        </section>

        {/* Features Section */}
        <section ref={featuresRef} className="py-20 px-4">
          <div className="max-w-7xl mx-auto">
            <div className="text-center mb-16">
              <h2 className="text-4xl lg:text-5xl font-bold text-white mb-6">
                Powerful Features for <span className="gradient-text">Smart Learning</span>
              </h2>
              <p className="text-xl text-gray-400 max-w-3xl mx-auto">
                Everything you need to excel in your studies, powered by cutting-edge AI technology
              </p>
            </div>

            <div ref={featureCardsRef} className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
              {features.map((feature, index) => {
                const Icon = feature.icon;
                return (
                  <div key={index} className="feature-card glass rounded-2xl p-8 border border-gray-700/50 card-hover">
                    <div className={`bg-gradient-to-br ${feature.color} p-4 rounded-2xl mb-6 inline-block glow-blue`}>
                      <Icon className="h-8 w-8 text-white" />
                    </div>
                    <h3 className="text-xl font-bold text-white mb-4">{feature.title}</h3>
                    <p className="text-gray-400 leading-relaxed">{feature.description}</p>
                  </div>
                );
              })}
            </div>
          </div>
        </section>

        {/* Testimonials Section */}
        <section ref={testimonialsRef} className="py-20 px-4 bg-gray-800/30">
          <div className="max-w-7xl mx-auto">
            <div className="text-center mb-16">
              <h2 className="text-4xl lg:text-5xl font-bold text-white mb-6">
                Loved by <span className="gradient-text">Students Everywhere</span>
              </h2>
              <p className="text-xl text-gray-400">
                See what students are saying about their success with STUBUD
              </p>
            </div>

            <div ref={testimonialsSectionRef} className="grid grid-cols-1 md:grid-cols-3 gap-8">
              {testimonials.map((testimonial, index) => (
                <div key={index} className="testimonial-card glass rounded-2xl p-6 border border-gray-700/50 card-hover">
                  <div className="flex items-center gap-1 mb-4">
                    {Array.from({ length: testimonial.rating }, (_, i) => (
                      <Star key={i} className="h-5 w-5 text-yellow-400 fill-current" />
                    ))}
                  </div>
                  <p className="text-gray-300 mb-4 italic">"{testimonial.text}"</p>
                  <div>
                    <p className="font-semibold text-white">{testimonial.name}</p>
                    <p className="text-sm text-gray-400">{testimonial.grade}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* CTA Section */}
        <section ref={ctaSectionRef} className="py-20 px-4 bg-gradient-to-r from-blue-600/20 to-purple-600/20">
          <div className="max-w-4xl mx-auto text-center">
            <h2 className="text-4xl lg:text-5xl font-bold text-white mb-6">
              Ready to Transform Your Studies?
            </h2>
            <p className="text-xl text-gray-300 mb-8">
              Join thousands of students who've improved their grades with STUBUD
            </p>
            
          </div>
        </section>

        {/* Footer */}
        <footer className="py-12 px-4 border-t border-gray-700/50">
          <div className="max-w-7xl mx-auto">
            <div className="flex items-center justify-center gap-3 mb-6">
              <div className="bg-gradient-to-br from-blue-500 to-purple-600 p-3 rounded-xl">
                <Brain className="h-6 w-6 text-white" />
              </div>
              <span className="text-xl font-bold gradient-text">STUBUD</span>
            </div>
            <p className="text-center text-gray-400">
              © 2025 STUBUD. All rights reserved. Empowering students with AI-powered learning.
            </p>
          </div>
        </footer>
      </div>
    </div>
  );
}