import React, { useState } from 'react';
import { Brain, Check, Star, Zap, Users, BarChart3, Crown, ArrowRight, Play, Shield, Sparkles, Target, BookOpen, TrendingUp, ExternalLink } from 'lucide-react';
import { useAuth } from '../contexts/AuthContext';
import { useToast } from '../hooks/useToast';

export function Landing() {
  const { signUp, signIn } = useAuth();
  const { showToast } = useToast();
  const [isSignUp, setIsSignUp] = useState(true);
  const [loading, setLoading] = useState(false);
  const [formData, setFormData] = useState({
    email: '',
    password: '',
    full_name: '',
    grade: '',
    school: ''
  });

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);

    try {
      if (isSignUp) {
        const { error } = await signUp(formData.email, formData.password, {
          full_name: formData.full_name,
          grade: formData.grade,
          school: formData.school
        });
        if (error) throw error;
        showToast('Account created! Welcome to STUBUD!', 'success');
      } else {
        const { error } = await signIn(formData.email, formData.password);
        if (error) throw error;
        showToast('Welcome back to STUBUD!', 'success');
      }
    } catch (error: any) {
      showToast(error.message, 'error');
    } finally {
      setLoading(false);
    }
  };

  const features = [
    {
      icon: Brain,
      title: 'AI-Powered Study Plans',
      description: 'Get personalized study schedules generated by advanced AI based on your exam dates and subjects.',
      color: 'from-blue-500 to-cyan-500'
    },
    {
      icon: Zap,
      title: 'Smart Flashcards',
      description: 'AI-generated flashcards with spaced repetition algorithm to maximize retention and learning efficiency.',
      color: 'from-purple-500 to-pink-500'
    },
    {
      icon: Target,
      title: 'Practice Test Engine',
      description: 'Unlimited AI-generated practice tests tailored to your curriculum with detailed performance analytics.',
      color: 'from-green-500 to-emerald-500'
    },
    {
      icon: BarChart3,
      title: 'Advanced Analytics',
      description: 'Deep insights into your learning patterns, progress tracking, and AI-powered recommendations.',
      color: 'from-orange-500 to-red-500'
    },
    {
      icon: Users,
      title: 'Study Groups',
      description: 'Join private study groups, compete on leaderboards, and collaborate with fellow students.',
      color: 'from-indigo-500 to-purple-500'
    },
    {
      icon: TrendingUp,
      title: 'Progress Tracking',
      description: 'Comprehensive progress monitoring with streak tracking, achievements, and performance metrics.',
      color: 'from-teal-500 to-blue-500'
    }
  ];

  const testimonials = [
    {
      name: 'Priya Sharma',
      grade: 'Class 12',
      text: 'STUBUD helped me improve my JEE preparation by 40%. The personalized study plans are incredible!',
      rating: 5
    },
    {
      name: 'Arjun Patel',
      grade: 'Class 10',
      text: 'The AI flashcards and practice tests made studying so much more effective. Highly recommend!',
      rating: 5
    },
    {
      name: 'Sneha Reddy',
      grade: 'Class 11',
      text: 'Study groups feature helped me connect with other students. We motivate each other every day!',
      rating: 5
    }
  ];

  const pricingFeatures = [
    'Unlimited AI Study Plans',
    'Smart Flashcard Generation',
    'Practice Test Engine',
    'Advanced Analytics & Insights',
    'Study Groups & Social Features',
    'Progress Tracking & Achievements',
    'Smart Notifications',
    'Offline Access',
    'Priority Support',
    'Export Study Materials'
  ];

  return (
    <div className="min-h-screen bg-gray-900 overflow-hidden">
      {/* Animated Background */}
      <div className="animated-gradient fixed inset-0 opacity-20"></div>
      <div className="absolute inset-0 overflow-hidden">
        <div className="absolute top-20 left-20 w-72 h-72 bg-blue-500/10 rounded-full blur-3xl animate-pulse"></div>
        <div className="absolute bottom-20 right-20 w-96 h-96 bg-purple-500/10 rounded-full blur-3xl animate-pulse animation-delay-1000"></div>
        <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-64 h-64 bg-cyan-500/10 rounded-full blur-3xl animate-pulse animation-delay-2000"></div>
      </div>

      <div className="relative z-10">
        {/* Hero Section */}
        <section className="min-h-screen flex items-center justify-center px-4 py-20">
          <div className="max-w-7xl mx-auto grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            {/* Left Side - Content */}
            <div className="text-center lg:text-left">
              <div className="flex items-center justify-center lg:justify-start gap-3 mb-6">
                <div className="relative">
                  <div className="bg-gradient-to-br from-blue-500 to-purple-600 p-4 rounded-2xl shadow-2xl glow-blue">
                    <Brain className="h-12 w-12 text-white" />
                  </div>
                  <Sparkles className="absolute -top-2 -right-2 h-8 w-8 text-yellow-400 animate-bounce" />
                  <Star className="absolute -bottom-1 -left-1 h-6 w-6 text-cyan-400 animate-pulse" />
                </div>
                <div>
                  <h1 className="text-5xl lg:text-6xl font-bold gradient-text">
                    STUBUD
                  </h1>
                  <p className="text-blue-300 text-lg">Your AI Study Buddy</p>
                </div>
              </div>

              <h2 className="text-4xl lg:text-5xl font-bold text-white mb-6 leading-tight">
                Transform Your Study Experience with{' '}
                <span className="gradient-text">AI Intelligence</span>
              </h2>

              <p className="text-xl text-gray-300 mb-8 leading-relaxed">
                Get personalized study plans, AI-generated flashcards, practice tests, and advanced analytics. 
                Join thousands of students who've improved their grades by 40% on average.
              </p>

              <div className="flex flex-col sm:flex-row gap-4 mb-8">
                <div className="flex items-center gap-2 text-green-400">
                  <Check className="h-5 w-5" />
                  <span>7-Day Free Trial</span>
                </div>
                <div className="flex items-center gap-2 text-blue-400">
                  <Shield className="h-5 w-5" />
                  <span>Secure Payment</span>
                </div>
                <div className="flex items-center gap-2 text-purple-400">
                  <Zap className="h-5 w-5" />
                  <span>Cancel Anytime</span>
                </div>
              </div>

              <div className="flex flex-col sm:flex-row gap-4">
               
              </div>
            </div>

            {/* Right Side - Auth Form */}
            <div className="glass rounded-2xl border border-gray-700/50 p-8 card-hover">
              <div className="text-center mb-6">
                <h3 className="text-2xl font-bold text-white mb-2">
                  {isSignUp ? 'Join STUBUD Today' : 'Welcome Back'}
                </h3>
                <p className="text-gray-400">
                  {isSignUp ? 'Start your AI-powered learning journey' : 'Continue your learning journey'}
                </p>
              </div>

              <form onSubmit={handleSubmit} className="space-y-4">
                {isSignUp && (
                  <>
                    <input
                      type="text"
                      required
                      value={formData.full_name}
                      onChange={(e) => setFormData(prev => ({ ...prev, full_name: e.target.value }))}
                      className="w-full px-4 py-3 rounded-xl bg-gray-800/50 border border-gray-600 focus:border-blue-500 focus:outline-none transition-all duration-300 text-white placeholder-gray-400"
                      placeholder="Full Name"
                    />
                    <div className="grid grid-cols-2 gap-4">
                      <input
                        type="text"
                        required
                        value={formData.grade}
                        onChange={(e) => setFormData(prev => ({ ...prev, grade: e.target.value }))}
                        className="w-full px-4 py-3 rounded-xl bg-gray-800/50 border border-gray-600 focus:border-blue-500 focus:outline-none transition-all duration-300 text-white placeholder-gray-400"
                        placeholder="Grade/Class"
                      />
                      <input
                        type="text"
                        value={formData.school}
                        onChange={(e) => setFormData(prev => ({ ...prev, school: e.target.value }))}
                        className="w-full px-4 py-3 rounded-xl bg-gray-800/50 border border-gray-600 focus:border-blue-500 focus:outline-none transition-all duration-300 text-white placeholder-gray-400"
                        placeholder="School"
                      />
                    </div>
                  </>
                )}

                <input
                  type="email"
                  required
                  value={formData.email}
                  onChange={(e) => setFormData(prev => ({ ...prev, email: e.target.value }))}
                  className="w-full px-4 py-3 rounded-xl bg-gray-800/50 border border-gray-600 focus:border-blue-500 focus:outline-none transition-all duration-300 text-white placeholder-gray-400"
                  placeholder="Email Address"
                />

                <input
                  type="password"
                  required
                  value={formData.password}
                  onChange={(e) => setFormData(prev => ({ ...prev, password: e.target.value }))}
                  className="w-full px-4 py-3 rounded-xl bg-gray-800/50 border border-gray-600 focus:border-blue-500 focus:outline-none transition-all duration-300 text-white placeholder-gray-400"
                  placeholder="Password"
                  minLength={6}
                />

                <button
                  type="submit"
                  disabled={loading}
                  className="w-full bg-gradient-to-r from-green-600 to-emerald-600 hover:from-green-700 hover:to-emerald-700 disabled:from-gray-600 disabled:to-gray-700 text-white font-bold py-3 px-6 rounded-xl transition-all duration-300 disabled:cursor-not-allowed"
                >
                  {loading ? (
                    <div className="flex items-center justify-center gap-2">
                      <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin"></div>
                      Please wait...
                    </div>
                  ) : (
                    isSignUp ? 'Create Account' : 'Sign In'
                  )}
                </button>
              </form>

              <div className="mt-6 text-center">
                <button
                  onClick={() => setIsSignUp(!isSignUp)}
                  className="text-blue-400 hover:text-blue-300 font-medium transition-colors duration-200"
                >
                  {isSignUp ? 'Already have an account? Sign in' : "Don't have an account? Join STUBUD"}
                </button>
              </div>

              {isSignUp && (
                <div className="mt-4 text-center">
                  <p className="text-xs text-gray-500">
                    By signing up, you agree to our Terms of Service and Privacy Policy
                  </p>
                </div>
              )}
            </div>
          </div>
        </section>

        {/* Features Section */}
        <section className="py-20 px-4">
          <div className="max-w-7xl mx-auto">
            <div className="text-center mb-16">
              <h2 className="text-4xl lg:text-5xl font-bold text-white mb-6">
                Powerful Features for <span className="gradient-text">Smart Learning</span>
              </h2>
              <p className="text-xl text-gray-400 max-w-3xl mx-auto">
                Everything you need to excel in your studies, powered by cutting-edge AI technology
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
              {features.map((feature, index) => {
                const Icon = feature.icon;
                return (
                  <div key={index} className="glass rounded-2xl p-8 border border-gray-700/50 card-hover">
                    <div className={`bg-gradient-to-br ${feature.color} p-4 rounded-2xl mb-6 inline-block glow-blue`}>
                      <Icon className="h-8 w-8 text-white" />
                    </div>
                    <h3 className="text-xl font-bold text-white mb-4">{feature.title}</h3>
                    <p className="text-gray-400 leading-relaxed">{feature.description}</p>
                  </div>
                );
              })}
            </div>
          </div>
        </section>

        {/* Testimonials Section */}
        <section className="py-20 px-4 bg-gray-800/30">
          <div className="max-w-7xl mx-auto">
            <div className="text-center mb-16">
              <h2 className="text-4xl lg:text-5xl font-bold text-white mb-6">
                Loved by <span className="gradient-text">Students Everywhere</span>
              </h2>
              <p className="text-xl text-gray-400">
                See what students are saying about their success with STUBUD
              </p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
              {testimonials.map((testimonial, index) => (
                <div key={index} className="glass rounded-2xl p-6 border border-gray-700/50 card-hover">
                  <div className="flex items-center gap-1 mb-4">
                    {Array.from({ length: testimonial.rating }, (_, i) => (
                      <Star key={i} className="h-5 w-5 text-yellow-400 fill-current" />
                    ))}
                  </div>
                  <p className="text-gray-300 mb-4 italic">"{testimonial.text}"</p>
                  <div>
                    <p className="font-semibold text-white">{testimonial.name}</p>
                    <p className="text-sm text-gray-400">{testimonial.grade}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Pricing Section */}
        <section className="py-20 px-4">
          <div className="max-w-4xl mx-auto">
            <div className="text-center mb-16">
              <h2 className="text-4xl lg:text-5xl font-bold text-white mb-6">
                Simple, <span className="gradient-text">Transparent Pricing</span>
              </h2>
              <p className="text-xl text-gray-400">
                Start with a 7-day free trial, then just ₹400/month for unlimited access
              </p>
            </div>

            <div className="glass rounded-3xl p-8 border border-yellow-500/30 bg-gradient-to-br from-yellow-500/10 to-orange-500/10 glow-blue">
              <div className="text-center mb-8">
                <div className="bg-gradient-to-r from-yellow-500 to-orange-500 text-white px-4 py-2 rounded-full text-sm font-medium mb-6 inline-block">
                  Most Popular Plan
                </div>
                <h3 className="text-3xl font-bold text-white mb-2">STUBUD Pro</h3>
                <div className="flex items-center justify-center gap-2 mb-4">
                  <span className="text-5xl font-bold text-yellow-400">₹400</span>
                  <span className="text-gray-400">/month</span>
                </div>
                <div className="bg-green-500/20 text-green-400 px-4 py-2 rounded-full text-sm font-medium inline-block">
                  7 Days Free Trial
                </div>
                <p className="text-xs text-gray-500 mt-2">
                  No charges during trial period
                </p>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-8">
                {pricingFeatures.map((feature, index) => (
                  <div key={index} className="flex items-center gap-3">
                    <Check className="h-5 w-5 text-green-400 flex-shrink-0" />
                    <span className="text-gray-300">{feature}</span>
                  </div>
                ))}
              </div>

              <button
                onClick={() => setIsSignUp(true)}
                className="w-full bg-gradient-to-r from-yellow-500 to-orange-500 hover:from-yellow-600 hover:to-orange-600 text-white font-bold py-4 px-8 rounded-xl transition-all duration-300 transform hover:scale-105 shadow-2xl"
              >
                <div className="flex items-center justify-center gap-2">
                  <Crown className="h-6 w-6" />
                  Start Your 7-Day Free Trial
                </div>
              </button>

              <p className="text-center text-sm text-gray-500 mt-4">
                Card required for trial • ₹400/month after trial • Cancel anytime
              </p>
            </div>
          </div>
        </section>

        {/* CTA Section */}
        <section className="py-20 px-4 bg-gradient-to-r from-blue-600/20 to-purple-600/20">
          <div className="max-w-4xl mx-auto text-center">
            <h2 className="text-4xl lg:text-5xl font-bold text-white mb-6">
              Ready to Transform Your Studies?
            </h2>
            <p className="text-xl text-gray-300 mb-8">
              Join thousands of students who've improved their grades with STUBUD
            </p>
            <button
              onClick={() => setIsSignUp(true)}
              className="bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700 text-white font-bold py-4 px-12 rounded-xl transition-all duration-300 transform hover:scale-105 shadow-2xl glow-blue btn-pulse text-lg"
            >
              Start 7-Day Free Trial Now
            </button>
          </div>
        </section>

        {/* Footer */}
        <footer className="py-12 px-4 border-t border-gray-700/50">
          <div className="max-w-7xl mx-auto">
            <div className="flex items-center justify-center gap-3 mb-6">
              <div className="bg-gradient-to-br from-blue-500 to-purple-600 p-3 rounded-xl">
                <Brain className="h-6 w-6 text-white" />
              </div>
              <span className="text-xl font-bold gradient-text">STUBUD</span>
            </div>
            <p className="text-center text-gray-400">
              © 2025 STUBUD. All rights reserved. Empowering students with AI-powered learning.
            </p>
          </div>
        </footer>
      </div>
    </div>
  );
}