import { useState } from 'react';
import { Link } from 'react-router-dom';
import { AlertTriangle, ArrowRight, BarChart3, BookOpen, CheckCircle2, ChevronRight, ClipboardList, FileText, GraduationCap, Lightbulb, MessageSquareText, Send, Sparkles, Target, Users, WandSparkles } from 'lucide-react';
import { useAuth } from '../contexts/AuthContext';

const focusStudents = [
  { name: 'Aarav Singh', detail: 'Ray optics · needs a visual explanation', initials: 'AS', tone: 'bg-[#dff2f7] text-[#317a8f]', action: 'Send a visual practice activity' },
  { name: 'Meera Patel', detail: 'Integration by parts · confidence is low', initials: 'MP', tone: 'bg-[#eee8ff] text-[#6e61ac]', action: 'Assign a gentle practice ladder' },
  { name: 'Rohan Das', detail: 'Completed early · ready for extension', initials: 'RD', tone: 'bg-[#e6f4da] text-[#619246]', action: 'Offer a challenge question' },
];

export default function TeacherStudio() {
  const { fullName } = useAuth();
  const [topic, setTopic] = useState('Ray optics: image formation');
  const [tab, setTab] = useState<'plan' | 'assess' | 'support'>('plan');
  const [notice, setNotice] = useState('');
  const firstName = (fullName || 'Teacher').split(/\s+/)[0];
  const showNotice = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(''), 2600); };

  return (
    <div className="min-h-screen bg-[#f4f8fc] px-4 py-6 sm:px-7 lg:px-10 lg:py-9 [font-family:Manrope,Inter,sans-serif]">
      <div className="mx-auto max-w-[1420px]">
        <div className="mb-7 flex flex-wrap items-start justify-between gap-4"><div><p className="text-[11px] font-extrabold uppercase tracking-[.15em] text-[#71909b]">Teacher workspace</p><h1 className="!mt-1 !text-3xl !font-extrabold !text-[#1d3b48]" style={{ fontFamily: 'Manrope, Inter, sans-serif' }}>Good morning, {firstName}. Your class is ready.</h1><p className="mt-2 text-sm font-semibold text-[#64818c]">Plan with less admin. Teach with more evidence.</p></div><Link to="/my-classes" className="inline-flex items-center gap-2 rounded-xl border border-[#dce9ed] bg-white px-4 py-2.5 text-xs font-extrabold text-[#53727e] shadow-sm">Open all classes <ChevronRight className="h-3.5 w-3.5" /></Link></div>

        <section className="grid gap-4 sm:grid-cols-3"><Metric icon={<Users className="h-5 w-5" />} value="32" label="students active today" tone="bg-[#e2f3f7] text-[#367c90]" /><Metric icon={<Target className="h-5 w-5" />} value="7" label="need a small next step" tone="bg-[#fff1ca] text-[#b67b19]" /><Metric icon={<CheckCircle2 className="h-5 w-5" />} value="84%" label="class readiness" tone="bg-[#e8f4dd] text-[#65934d]" /></section>

        <section className="mt-6 grid gap-6 xl:grid-cols-[1.08fr_.92fr]">
          <div className="rounded-[30px] bg-white p-6 shadow-[0_12px_32px_rgba(37,75,89,.06)] ring-1 ring-[#e0ebef] sm:p-7"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[11px] font-extrabold uppercase tracking-[.13em] text-[#72909b]">Today’s teaching loop</p><h2 className="!mt-1 !text-2xl !font-extrabold !text-[#264552]" style={{ fontFamily: 'Manrope, Inter, sans-serif' }}>Prepare, teach, respond</h2></div><div className="flex rounded-xl bg-[#f3f8f9] p-1">{(['plan', 'assess', 'support'] as const).map((item) => <button key={item} onClick={() => setTab(item)} className={`rounded-lg px-3 py-2 text-[10px] font-extrabold capitalize ${tab === item ? 'bg-white text-[#326f83] shadow-sm' : 'text-[#8299a1]'}`}>{item}</button>)}</div></div>
            {tab === 'plan' && <div className="mt-6"><div className="rounded-[23px] bg-[#eaf7fa] p-5"><div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-white text-[#4c98ab] shadow-sm"><WandSparkles className="h-5 w-5" /></span><div><p className="text-sm font-extrabold text-[#315767]">Build a curriculum-aware lesson</p><p className="mt-1 text-xs font-bold leading-5 text-[#6c909c]">Nia can draft an objective, a misconception check, activity ideas, and an exit ticket in one place.</p></div></div><input value={topic} onChange={(event) => setTopic(event.target.value)} className="mt-5 w-full rounded-xl border border-[#c9e3ea] bg-white px-4 py-3 text-sm font-bold text-[#385865] outline-none focus:ring-2 focus:ring-[#67aebf]/30" /><button onClick={() => showNotice(`Lesson outline for “${topic}” is ready to refine.`)} className="mt-3 inline-flex items-center gap-2 rounded-xl bg-[#2e6c83] px-4 py-3 text-xs font-extrabold text-white"><Sparkles className="h-4 w-4" /> Draft lesson plan</button></div><LessonStep number="1" title="Open with a misconception check" detail="Ask students to predict where the image appears before drawing a ray." /><LessonStep number="2" title="Make thinking visible" detail="Use a 3-minute pair explanation before formal notation." /><LessonStep number="3" title="Capture evidence" detail="Finish with one question that reveals the model, not recall." /></div>}
            {tab === 'assess' && <div className="mt-6 grid gap-3"><ActionCard icon={<ClipboardList className="h-5 w-5" />} title="Build a useful check for understanding" detail="Generate a short, mixed-difficulty question set aligned to today’s objective." action="Create question bank" onClick={() => showNotice('Question bank builder opened with today’s topic.')} /><ActionCard icon={<FileText className="h-5 w-5" />} title="Turn classwork into feedback" detail="Bring submissions, quick grades, and follow-up suggestions together." action="Review submitted work" to="/my-classes" /></div>}
            {tab === 'support' && <div className="mt-6 grid gap-3"><ActionCard icon={<BarChart3 className="h-5 w-5" />} title="See the learning pattern" detail="View weak concepts, effort signals, and what changed after an intervention." action="Open learning signals" to="/my-classes" /><ActionCard icon={<MessageSquareText className="h-5 w-5" />} title="Send one helpful next step" detail="Give the right learner a nudge, activity, or challenge without extra planning." action="Choose a learner" onClick={() => showNotice('Select a learner from the attention queue.')} /></div>}
          </div>
          <div className="rounded-[30px] bg-[#fdf0c9] p-6"><div className="flex items-start justify-between"><div><p className="text-[11px] font-extrabold uppercase tracking-[.13em] text-[#a57622]">Attention queue</p><h2 className="!mt-1 !text-2xl !font-extrabold !text-[#4a391d]" style={{ fontFamily: 'Manrope, Inter, sans-serif' }}>Three students to notice</h2></div><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-white text-[#c18118] shadow-sm"><AlertTriangle className="h-5 w-5" /></span></div><p className="mt-3 text-xs font-semibold leading-5 text-[#83693a]">Not a ranking. A calm, actionable view of who may benefit from your attention today.</p><div className="mt-5 space-y-3">{focusStudents.map((student) => <div key={student.name} className="rounded-2xl bg-white/75 p-3.5 shadow-sm"><div className="flex items-center gap-3"><span className={`flex h-9 w-9 items-center justify-center rounded-xl text-[10px] font-black ${student.tone}`}>{student.initials}</span><div className="min-w-0 flex-1"><p className="text-xs font-extrabold text-[#4d422d]">{student.name}</p><p className="mt-0.5 truncate text-[10px] font-bold text-[#88764e]">{student.detail}</p></div></div><button onClick={() => showNotice(`${student.action} for ${student.name} is queued.`)} className="mt-3 text-[10px] font-extrabold text-[#8b641d]">{student.action} <ArrowRight className="inline h-3 w-3" /></button></div>)}</div><div className="mt-5 rounded-2xl border border-[#e8cf91] bg-[#fff8df] p-3 text-[11px] font-bold leading-5 text-[#876a32]"><Lightbulb className="mr-1 inline h-3.5 w-3.5" /> The strongest intervention is usually small, specific, and delivered early.</div></div>
        </section>
        <section className="mt-6 grid gap-4 md:grid-cols-3"><Resource icon={<BookOpen className="h-5 w-5" />} title="Your classes" detail="Classroom, resources, announcements, and assignments" to="/my-classes" /><Resource icon={<GraduationCap className="h-5 w-5" />} title="Student evidence" detail="Notebook checks and mastery activity outcomes" to="/teacher/grader" /><Resource icon={<Send className="h-5 w-5" />} title="Share useful updates" detail="Bring class progress and next steps into one clear update" to="/my-classes" /></section>
      </div>
      {notice && <div className="fixed bottom-5 left-1/2 z-50 -translate-x-1/2 rounded-full bg-[#284d5a] px-5 py-3 text-xs font-extrabold text-white shadow-2xl">{notice}</div>}
    </div>
  );
}

function Metric({ icon, value, label, tone }: { icon: React.ReactNode; value: string; label: string; tone: string }) { return <div className={`rounded-[23px] p-5 ${tone}`}><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-white/70 shadow-sm">{icon}</span><p className="mt-6 text-2xl font-black">{value}</p><p className="mt-1 text-[11px] font-extrabold opacity-75">{label}</p></div>; }
function LessonStep({ number, title, detail }: { number: string; title: string; detail: string }) { return <div className="flex gap-3 border-b border-[#edf2f3] py-4 last:border-0"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-[#edf7f8] text-[10px] font-black text-[#4d91a2]">{number}</span><div><p className="text-xs font-extrabold text-[#355460]">{title}</p><p className="mt-1 text-[11px] font-semibold leading-5 text-[#7c969e]">{detail}</p></div></div>; }
function ActionCard({ icon, title, detail, action, onClick, to }: { icon: React.ReactNode; title: string; detail: string; action: string; onClick?: () => void; to?: string }) { const content = <><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#ecf7f9] text-[#4b96a9]">{icon}</span><span className="min-w-0 flex-1"><span className="block text-sm font-extrabold text-[#31515c]">{title}</span><span className="mt-1 block text-[11px] font-semibold leading-5 text-[#7b959e]">{detail}</span><span className="mt-3 block text-[11px] font-extrabold text-[#367c90]">{action} <ArrowRight className="inline h-3.5 w-3.5" /></span></span></>; return to ? <Link to={to} className="flex gap-3 rounded-2xl border border-[#e0ecef] p-4 transition-colors hover:bg-[#f8fcfc]">{content}</Link> : <button onClick={onClick} className="flex w-full gap-3 rounded-2xl border border-[#e0ecef] p-4 text-left transition-colors hover:bg-[#f8fcfc]">{content}</button>; }
function Resource({ icon, title, detail, to }: { icon: React.ReactNode; title: string; detail: string; to: string }) { return <Link to={to} className="flex items-center gap-3 rounded-[22px] bg-white p-4 shadow-[0_8px_24px_rgba(37,75,89,.05)] ring-1 ring-[#e1ecef] hover:-translate-y-0.5"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#edf7f8] text-[#4b91a3]">{icon}</span><span className="min-w-0 flex-1"><span className="block text-xs font-extrabold text-[#365460]">{title}</span><span className="mt-1 block truncate text-[10px] font-bold text-[#839aa2]">{detail}</span></span><ChevronRight className="h-4 w-4 text-[#8fa5ad]" /></Link>; }
