-- ============================================
-- Mastery Receipts: signed proof-of-learning
-- Generated by Prove-It Mode Socratic loops.
-- ============================================

CREATE TABLE IF NOT EXISTS public.mastery_receipts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  slug TEXT NOT NULL UNIQUE,           -- public share URL segment
  subject TEXT NOT NULL,
  topic TEXT NOT NULL,
  level TEXT NOT NULL DEFAULT 'intermediate' CHECK (level IN ('beginner', 'intermediate', 'advanced')),
  rigor_score NUMERIC NOT NULL DEFAULT 0,  -- 0..10, set by grader
  qa_log JSONB NOT NULL DEFAULT '[]'::jsonb, -- [{question, student_answer, verdict, critique}]
  verdict TEXT NOT NULL DEFAULT 'pending' CHECK (verdict IN ('pending', 'passed', 'failed')),
  public_visible BOOLEAN NOT NULL DEFAULT true,
  pdf_url TEXT,                        -- Supabase Storage path
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_mastery_receipts_user ON public.mastery_receipts(user_id);
CREATE INDEX IF NOT EXISTS idx_mastery_receipts_slug ON public.mastery_receipts(slug);
-- RLS
ALTER TABLE public.mastery_receipts ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='mastery_receipts' AND policyname='mastery_select_own_or_public'
  ) THEN
    CREATE POLICY mastery_select_own_or_public ON public.mastery_receipts
      FOR SELECT USING (auth.uid() = user_id OR public_visible = true);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='mastery_receipts' AND policyname='mastery_insert_own'
  ) THEN
    CREATE POLICY mastery_insert_own ON public.mastery_receipts
      FOR INSERT WITH CHECK (auth.uid() = user_id);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='mastery_receipts' AND policyname='mastery_update_own'
  ) THEN
    CREATE POLICY mastery_update_own ON public.mastery_receipts
      FOR UPDATE USING (auth.uid() = user_id);
  END IF;
END $$;
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='mastery_receipts' AND policyname='mastery_delete_own'
  ) THEN
    CREATE POLICY mastery_delete_own ON public.mastery_receipts
      FOR DELETE USING (auth.uid() = user_id);
  END IF;
END $$;
-- Trigger for updated_at
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'trg_mastery_receipts_updated_at'
  ) THEN
    CREATE TRIGGER trg_mastery_receipts_updated_at
      BEFORE UPDATE ON public.mastery_receipts
      FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
  END IF;
END $$;
NOTIFY pgrst, 'reload schema';
